services:
  # Start the frontend application
  app:
    container_name: Frontend
    # Copy the Frontend folder into app
    build:
      context: ./Frontend
    # Environment variable just in case.
    environment:
      NODE_ENV: production
    # Open localhost ports
    ports:
      - 8228:3000
    # Copy volumes for file retention.
    volumes:
      - ".:/Frontend/"
      - /Frontend/node_modules
  
  server:
    container_name: Backend
    build: ./Backend
    environment:
      - NODE_ENV: production
    
  database: