services:
  app:
    container_name: Frontend
    build:
      context: ./Frontend
    environment:
      NODE_ENV: production
    # command: serve -s build
    ports:
      - 8228:3000
    volumes:
      - ".:/Frontend/"
      - /Frontend/node_modules

  # mongo_db:
  #   container_name: Code
  #   image: "mongo"
  #   volumes:
  #     - mongo_db:/data/db
  #   ports:
  #     - 27017:27017

  sqldb:
    build: ./SQL
    ports:
        - 1433:1433